[workspace]
[changelog]
commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^deprecated", group = "deprecated" },
  { message = "^doc", group = "Documentation" },
  { message = "^refactor", group = "Refactor" },
  { message = "^fix", group = "fixed" },
  { message = "^security", group = "security" },
  { message = "^test", group = "Testing" },
  { message = "^chore(deps)", group = "Dependencies" },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^.*", skip = true },
]
